name: run_tests

on:
    push:
        branches: [ main ] 
    pull_request:


jobs:
    run-pytests-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: ./
              with:
                    src: python_checkout/tests/test_app.py
                    args: ""

    run-cargotest-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Setup Rust
              run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

            - name: run cargo test
              run: cargo test
              working-directory: ./rust_checkout
          
