name: run_tests

on:
    push:
        branches: [ main ] 
    pull_request:


jobs:
    run-pytests-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: ./
              with:
                    src: python_checkout/tests/test_app.py
                    args: ""

    run-cargotest-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Setup Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable

            - uses: ./
              with:
                  src: rust_checkout/Cargo.toml
                  args: ""

            - name: run cargo test
              run: cargo test
          
